image: golang:1.22

stages:
  - build

build:
  stage: build
  script:
    - go build -o bin/main_ci main.go
    - old_hash=$(sha256sum bin/main | awk '{ print $1 }');
      new_hash=$(sha256sum bin/main_ci | awk '{ print $1 }');
      if [ "$old_hash" = "$new_hash" ]; then
        echo "Check build pass - checksums are identical.";
      else
        echo "Check build fail - checksums differ.";
        exit 1;
      fi

  only:
    - main
    - dev
