image: golang:1.22

stages:
  - build

build:
  stage: build
  script:
    - go build -trimpath -ldflags="-s -w" -o bin/main_ci main.go
    - if cmp -s bin/main_ci bin/main; then
        echo "Check build pass - binaries are identical.";
      else
        echo "Check build fail - binaries differ.";
        exit 1;
      fi
  only:
    - main
    - dev
