image: golang:1.20

stages:
  - build

before_script:
  - export GOPATH="/go"
  - export PATH=$GOPATH/bin:$PATH
  - go env

build:
  stage: build
  script:
    - go build -o bin/main main.go
  only:
    - main
