image: golang:1.22

stages:
  - build

build:
  stage: build
  script:
    - go build -o bin/main_ci main.go
    - if cmp bin/main_ci bin/main; then echo "check build pass"; else echo "check build fail"; exit 1; fi
  only:
    - main
    - dev
